# Define all services (containers)
services:
  # MongoDB service
  mongodb:
    # Use official mongoDB image
    image: mongo:latest
    # Always restart unless forcibly stop the process.
    restart: unless-stopped
    ports:
      - "27017:27017"
    # Create volume within src directory
    volumes:
      - ./database/mongodb-data:/data/db
  # Backend service
  expressjs:
    # Build the docker image from the dockerfile in the current dir
    build:
      dockerfile: Dockerfile.dev

    # Map port 8000 inside the container to port 8000 on the host machine
    ports:
      - "8000:8000"

    # Load env variables from the .env file
    env_file:
      - .env
    # Override environment variable to indicate containerized environment
    environment:
      - IS_DOCKERIZED=true

    # Wait for mongo servvice to start
    depends_on:
      - mongodb

    # Override the default command and run npm start
    command: pnpm start
