services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
  expressjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - IS_DOCKERIZED=true
      - NODE_ENV=prod
    depends_on:
      - mongodb
    command: ["node", "dist/index.js"]

volumes:
  mongodb-data:
