name: BrainBytes CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm and Node.js
        uses: pnpm/action-setup@v2
        with:
          version: "10.10.0"
          node-version: "24.1.0"
          cache: "pnpm"

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "24.1.0"
      #     cache: "pnpm"

      - name: Install dependencies
        working-directory: ./src
        run: pnpm install --no-frozen-lockfile

      - name: Lint source code
        working-directory: ./src
        run: pnpm lint

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    environment: GitHub actions
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      MONGO_URI_DOCKER: ${{secrets.MONGO_URI_DOCKER}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm and Node.js
        uses: pnpm/action-setup@v2
        with:
          version: "10.10.0"
          node-version: "24.1.0"
          cache: "pnpm"

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "24.1.0"
      #     cache: "pnpm"

      - name: Install dependencies
        working-directory: ./src
        run: pnpm install --no-frozen-lockfile

      - name: Run backend tests
        working-directory: ./src
        run: pnpm test
