name: BrainBytes CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: GitHub actions
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      MONGO_URI_DOCKER: ${{secrets.MONGO_URI_DOCKER}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./src
        run: pnpm install --no-frozen-lockfile

      - name: Run backend tests
        working-directory: ./src
        run: pnpm test
